import { maskAddress, maskEmail, maskPhone, type MaskedLead } from "./leads";

/**
 * Stand-in for `select * from leads_masked`.
 *
 * Rows carry contact values so both gated states can be exercised; the real
 * view returns null for those columns to an unpaid business. When Supabase is
 * connected, replace `getVendorLeads` with the query — the row shape is
 * already the view's shape, so nothing downstream changes.
 */

const HOUR = 60 * 60 * 1000;

function hoursAgo(n: number): string {
  return new Date(Date.now() - n * HOUR).toISOString();
}

type LeadRow = Omit<
  MaskedLead,
  "isUnlocked" | "phonePreview" | "emailPreview" | "addressPreview"
>;

const ROWS: LeadRow[] = [
  {
    id: "lead-1",
    customerName: "Sarah Jenkins",
    city: "Gulberg III, Lahore",
    roomType: "Living Room",
    styleSlug: "japandi",
    status: "new",
    createdAt: hoursAgo(2),
    captureStatus: "4/4 Photos",
    phone: "+92 300 1234567",
    email: "sarah.jenkins@gmail.com",
    fullAddress: "House 42, Street 7, Gulberg III, Lahore",
    message:
      "Access via service elevator. Please bring physical samples for the oak flooring if possible.",
  },
  {
    id: "lead-2",
    customerName: "Michael Chen",
    city: "F-7, Islamabad",
    roomType: "Bedroom",
    styleSlug: "warm_neutral",
    status: "contacted",
    createdAt: hoursAgo(26),
    captureStatus: "4/4 Photos",
    phone: "+92 321 9876543",
    email: "m.chen@outlook.com",
    fullAddress: "Apartment 9B, Silver Oaks, F-7, Islamabad",
    message: "Weekends only for the site visit.",
  },
  {
    id: "lead-3",
    customerName: "Elena Rossi",
    city: "DHA Phase 5, Karachi",
    roomType: "Home Office",
    styleSlug: "minimal",
    status: "completed",
    createdAt: hoursAgo(72),
    captureStatus: "4/4 Photos",
    phone: "+92 333 4567890",
    email: "elena.rossi@studio.pk",
    fullAddress: "Villa 17, Khayaban-e-Shahbaz, DHA Phase 5, Karachi",
    message: null,
  },
  {
    id: "lead-4",
    customerName: "Bilal Ahmed",
    city: "Bahria Town, Rawalpindi",
    roomType: "Dining Room",
    styleSlug: "scandinavian",
    status: "new",
    createdAt: hoursAgo(5),
    captureStatus: "4/4 Photos",
    phone: "+92 345 2223344",
    email: "bilal.ahmed@gmail.com",
    fullAddress: "Plot 88, Sector C, Bahria Town, Rawalpindi",
    message: "Budget is firm. Prefer locally sourced timber.",
  },

  // --- Historical leads, so the 6-month trend is computed from real rows ---
  {
    id: "lead-6",
    customerName: "Tariq Butt",
    city: "Model Town, Lahore",
    roomType: "Home Office",
    styleSlug: "grey",
    status: "completed",
    createdAt: hoursAgo(3594),
    captureStatus: "4/4 Photos",
    phone: "+92 342 4186027",
    email: "tariq.butt@example.com",
    fullAddress: "House 51, Street 33, Bahria Town, Rawalpindi",
    message: null,
  },
  {
    id: "lead-7",
    customerName: "Mehwish Javed",
    city: "G-11, Islamabad",
    roomType: "Bedroom",
    styleSlug: "warm_neutral",
    status: "completed",
    createdAt: hoursAgo(3557),
    captureStatus: "4/4 Photos",
    phone: "+92 338 6090228",
    email: "mehwish.javed@example.com",
    fullAddress: "House 40, Street 6, Model Town, Lahore",
    message: null,
  },
  {
    id: "lead-8",
    customerName: "Fatima Aslam",
    city: "Clifton, Karachi",
    roomType: "Living Room",
    styleSlug: "industrial",
    status: "completed",
    createdAt: hoursAgo(3520),
    captureStatus: "4/4 Photos",
    phone: "+92 338 3642312",
    email: "fatima.aslam@example.com",
    fullAddress: "House 163, Street 1, G-11, Islamabad",
    message: null,
  },
  {
    id: "lead-9",
    customerName: "Sana Siddiqui",
    city: "Gulberg III, Lahore",
    roomType: "Living Room",
    styleSlug: "scandinavian",
    status: "contacted",
    createdAt: hoursAgo(3483),
    captureStatus: "4/4 Photos",
    phone: "+92 325 1504702",
    email: "sana.siddiqui@example.com",
    fullAddress: "House 122, Street 21, Bahria Town, Rawalpindi",
    message: null,
  },
  {
    id: "lead-10",
    customerName: "Rizwan Butt",
    city: "F-7, Islamabad",
    roomType: "Kids Room",
    styleSlug: "scandinavian",
    status: "completed",
    createdAt: hoursAgo(2874),
    captureStatus: "4/4 Photos",
    phone: "+92 328 9384802",
    email: "rizwan.butt@example.com",
    fullAddress: "House 5, Street 6, Bahria Town, Rawalpindi",
    message: null,
  },
  {
    id: "lead-11",
    customerName: "Mehwish Hussain",
    city: "Bahria Town, Rawalpindi",
    roomType: "Kids Room",
    styleSlug: "warm_neutral",
    status: "completed",
    createdAt: hoursAgo(2837),
    captureStatus: "4/4 Photos",
    phone: "+92 326 6289473",
    email: "mehwish.hussain@example.com",
    fullAddress: "House 62, Street 33, DHA Phase 5, Karachi",
    message: null,
  },
  {
    id: "lead-12",
    customerName: "Hina Siddiqui",
    city: "Model Town, Lahore",
    roomType: "Living Room",
    styleSlug: "industrial",
    status: "contacted",
    createdAt: hoursAgo(2800),
    captureStatus: "4/4 Photos",
    phone: "+92 316 5880540",
    email: "hina.siddiqui@example.com",
    fullAddress: "House 102, Street 5, Gulberg III, Lahore",
    message: null,
  },
  {
    id: "lead-13",
    customerName: "Shahid Rana",
    city: "Gulberg III, Lahore",
    roomType: "Bedroom",
    styleSlug: "scandinavian",
    status: "new",
    createdAt: hoursAgo(2763),
    captureStatus: "4/4 Photos",
    phone: "+92 313 8885078",
    email: "shahid.rana@example.com",
    fullAddress: "House 100, Street 26, Bahria Town, Rawalpindi",
    message: null,
  },
  {
    id: "lead-14",
    customerName: "Omar Javed",
    city: "Clifton, Karachi",
    roomType: "Bedroom",
    styleSlug: "modern",
    status: "completed",
    createdAt: hoursAgo(2154),
    captureStatus: "4/4 Photos",
    phone: "+92 331 2462037",
    email: "omar.javed@example.com",
    fullAddress: "House 83, Street 22, Gulberg III, Lahore",
    message: null,
  },
  {
    id: "lead-15",
    customerName: "Nadia Nawaz",
    city: "Gulberg III, Lahore",
    roomType: "Bedroom",
    styleSlug: "scandinavian",
    status: "completed",
    createdAt: hoursAgo(2117),
    captureStatus: "4/4 Photos",
    phone: "+92 316 1183794",
    email: "nadia.nawaz@example.com",
    fullAddress: "House 19, Street 30, G-11, Islamabad",
    message: null,
  },
  {
    id: "lead-16",
    customerName: "Tariq Khan",
    city: "Clifton, Karachi",
    roomType: "Kids Room",
    styleSlug: "scandinavian",
    status: "contacted",
    createdAt: hoursAgo(2080),
    captureStatus: "4/4 Photos",
    phone: "+92 338 9537345",
    email: "tariq.khan@example.com",
    fullAddress: "House 52, Street 9, Bahria Town, Rawalpindi",
    message: null,
  },
  {
    id: "lead-17",
    customerName: "Mehwish Qureshi",
    city: "Gulberg III, Lahore",
    roomType: "Home Office",
    styleSlug: "industrial",
    status: "completed",
    createdAt: hoursAgo(1434),
    captureStatus: "4/4 Photos",
    phone: "+92 323 1007900",
    email: "mehwish.qureshi@example.com",
    fullAddress: "House 73, Street 38, DHA Phase 5, Karachi",
    message: null,
  },
  {
    id: "lead-18",
    customerName: "Hina Farooq",
    city: "F-7, Islamabad",
    roomType: "Home Office",
    styleSlug: "warm_neutral",
    status: "contacted",
    createdAt: hoursAgo(1397),
    captureStatus: "4/4 Photos",
    phone: "+92 312 3455489",
    email: "hina.farooq@example.com",
    fullAddress: "House 58, Street 29, DHA Phase 5, Karachi",
    message: null,
  },
  {
    id: "lead-19",
    customerName: "Hina Nawaz",
    city: "Model Town, Lahore",
    roomType: "Dining Room",
    styleSlug: "modern",
    status: "new",
    createdAt: hoursAgo(1360),
    captureStatus: "4/4 Photos",
    phone: "+92 334 2231423",
    email: "hina.nawaz@example.com",
    fullAddress: "House 23, Street 6, F-7, Islamabad",
    message: null,
  },
  {
    id: "lead-20",
    customerName: "Rizwan Rana",
    city: "F-7, Islamabad",
    roomType: "Living Room",
    styleSlug: "luxury",
    status: "new",
    createdAt: hoursAgo(1323),
    captureStatus: "4/4 Photos",
    phone: "+92 333 8603570",
    email: "rizwan.rana@example.com",
    fullAddress: "House 36, Street 38, Bahria Town, Rawalpindi",
    message: null,
  },
  {
    id: "lead-21",
    customerName: "Shahid Javed",
    city: "F-7, Islamabad",
    roomType: "Home Office",
    styleSlug: "minimal",
    status: "completed",
    createdAt: hoursAgo(714),
    captureStatus: "4/4 Photos",
    phone: "+92 319 6214548",
    email: "shahid.javed@example.com",
    fullAddress: "House 62, Street 40, F-7, Islamabad",
    message: null,
  },
  {
    id: "lead-22",
    customerName: "Adnan Farooq",
    city: "F-7, Islamabad",
    roomType: "Kids Room",
    styleSlug: "scandinavian",
    status: "contacted",
    createdAt: hoursAgo(677),
    captureStatus: "4/4 Photos",
    phone: "+92 334 9095278",
    email: "adnan.farooq@example.com",
    fullAddress: "House 158, Street 6, Bahria Town, Rawalpindi",
    message: null,
  },
  {
    id: "lead-23",
    customerName: "Hina Siddiqui",
    city: "Gulberg III, Lahore",
    roomType: "Living Room",
    styleSlug: "modern",
    status: "new",
    createdAt: hoursAgo(640),
    captureStatus: "4/4 Photos",
    phone: "+92 325 7570141",
    email: "hina.siddiqui@example.com",
    fullAddress: "House 69, Street 27, G-11, Islamabad",
    message: null,
  },
];

/** Applies the gate the same way the database view would. */
export function getVendorLeads(hasPaidAccess: boolean): MaskedLead[] {
  return ROWS.map((row) => ({
    ...row,
    isUnlocked: hasPaidAccess,
    // Masked previews are derived here, on the server. When the real view is
    // wired up these come from the database too -- the unmasked value must
    // never cross the network to an unpaid vendor.
    phonePreview: maskPhone(row.phone ?? ""),
    emailPreview: maskEmail(row.email ?? ""),
    addressPreview: maskAddress(row.fullAddress ?? ""),
    phone: hasPaidAccess ? row.phone : null,
    email: hasPaidAccess ? row.email : null,
    fullAddress: hasPaidAccess ? row.fullAddress : null,
    message: hasPaidAccess ? row.message : null,
  }));
}

export function getVendorLead(id: string, hasPaidAccess: boolean): MaskedLead | undefined {
  return getVendorLeads(hasPaidAccess).find((lead) => lead.id === id);
}
