"""Zero-cost image generation, behind a provider abstraction.

Providers are selected by IMAGE_GENERATOR_PROVIDER and tried in order, so a
provider going away degrades the run rather than ending it:

  pollinations  primary. No auth, no billing, no account.
  huggingface   fallback. Uses HUGGINGFACE_API_TOKEN.

Generated bytes go straight into the private `generated-designs` bucket; the
caller mints a signed URL. Nothing is served from a provider's own URL, which
would break the moment they rotate or expire it.
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass
from urllib.parse import quote

import httpx

from app.core.config import get_settings
from app.services.storage import UploadError, upload_wall_photo

logger = logging.getLogger(__name__)

POLLINATIONS_URL = "https://image.pollinations.ai/prompt/{prompt}"
HUGGINGFACE_URL = "https://router.huggingface.co/hf-inference/models/{model}"

DEFAULT_WIDTH = 1024
DEFAULT_HEIGHT = 768


class GenerationError(RuntimeError):
    """No provider could produce an image."""


@dataclass
class RenderedImage:
    """One generated concept, already stored."""

    storage_path: str
    provider: str
    seed: int
    width: int
    height: int
    size_bytes: int


async def _pollinations(
    client: httpx.AsyncClient, prompt: str, *, seed: int, width: int, height: int, timeout: int
) -> bytes:
    """Primary engine. Free, unauthenticated, rate-limited but reliable."""
    url = POLLINATIONS_URL.format(prompt=quote(prompt[:1800], safe=""))
    response = await client.get(
        url,
        params={
            "width": width,
            "height": height,
            "nologo": "true",
            "seed": seed,
            "model": "flux",
        },
        timeout=timeout,
        follow_redirects=True,
    )
    if response.status_code != 200:
        raise GenerationError(f"Pollinations returned {response.status_code}.")
    if not response.headers.get("content-type", "").startswith("image/"):
        raise GenerationError("Pollinations did not return an image.")
    return response.content


async def _huggingface(
    client: httpx.AsyncClient, prompt: str, *, seed: int, width: int, height: int, timeout: int
) -> bytes:
    """Fallback engine via the Hugging Face Inference router."""
    settings = get_settings()
    if not settings.huggingface_api_token:
        raise GenerationError("HUGGINGFACE_API_TOKEN is not set.")

    response = await client.post(
        HUGGINGFACE_URL.format(model=settings.huggingface_image_model),
        headers={"Authorization": f"Bearer {settings.huggingface_api_token}"},
        json={
            "inputs": prompt[:1800],
            "parameters": {"width": width, "height": height, "seed": seed},
        },
        timeout=timeout,
    )
    if response.status_code == 410:
        # The free hf-inference provider stopped serving text-to-image models.
        # Reported precisely so this is not mistaken for a bad token.
        raise GenerationError(
            "Hugging Face: model deprecated on the free hf-inference provider. "
            "A paid provider (fal, replicate, together) would be required."
        )
    if response.status_code == 503:
        raise GenerationError("Hugging Face: model is loading, try again shortly.")
    if response.status_code != 200:
        raise GenerationError(f"Hugging Face returned {response.status_code}: {response.text[:160]}")
    if not response.headers.get("content-type", "").startswith("image/"):
        raise GenerationError("Hugging Face did not return an image.")
    return response.content


_PROVIDERS = {
    "pollinations": _pollinations,
    "huggingface": _huggingface,
}


def provider_chain() -> list[str]:
    """Configured provider first, then the others as fallbacks."""
    preferred = (get_settings().image_generator_provider or "pollinations").lower()
    chain = [preferred] if preferred in _PROVIDERS else ["pollinations"]
    chain += [name for name in _PROVIDERS if name not in chain]
    return chain


async def generate_image(
    prompt: str,
    *,
    project_id: str,
    index: int = 0,
    seed: int | None = None,
    width: int = DEFAULT_WIDTH,
    height: int = DEFAULT_HEIGHT,
) -> RenderedImage:
    """Render one concept and store it. Raises GenerationError if all fail."""
    settings = get_settings()
    # Deterministic per project and slot, so a retry reproduces the same
    # composition instead of silently returning a different room.
    actual_seed = seed if seed is not None else (abs(hash(project_id)) % 100_000) + index
    timeout = settings.generation_timeout_seconds

    failures: list[str] = []
    async with httpx.AsyncClient() as client:
        for name in provider_chain():
            try:
                data = await _PROVIDERS[name](
                    client, prompt, seed=actual_seed, width=width, height=height, timeout=timeout
                )
            except Exception as exc:  # noqa: BLE001 - try the next provider
                logger.warning("Image provider %s failed: %s", name, exc)
                failures.append(f"{name}: {exc}")
                continue

            try:
                stored = upload_wall_photo(
                    project_id=project_id,
                    wall_angle=f"concept-{index}",
                    data=data,
                    bucket=settings.generated_designs_bucket,
                )
            except UploadError as exc:
                failures.append(f"{name}: stored badly ({exc})")
                continue

            logger.info(
                "Rendered concept %s for %s via %s (%d bytes)",
                index, project_id, name, stored.size_bytes,
            )
            return RenderedImage(
                storage_path=stored.path,
                provider=name,
                seed=actual_seed,
                width=width,
                height=height,
                size_bytes=stored.size_bytes,
            )

    raise GenerationError("; ".join(failures) or "No image provider is configured.")


def new_concept_slug() -> str:
    return uuid.uuid4().hex[:8]
